# Site settings
title: Zhou Weimin
email: weimin.zhou@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a PhD student in Universitat Autonoma de Barcelona and Barcelona GSE.
  I study Economics Analysis.
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://jabranham.com" # the base hostname & protocol for your site
twitter_username: chouwm924
github_username:  zhouweimin233
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
